// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepoLens.Infrastructure.Persistence;

#nullable disable

namespace RepoLens.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepoLensDbContext))]
    [Migration("20260922022854_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoLens.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommitHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.AnalysisIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("analysis_issues", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.ApiEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Controller")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("SymbolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SymbolId");

                    b.ToTable("api_endpoints", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.CodeSymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SourceFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.Property<string>("SymbolType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("SourceFileId");

                    b.ToTable("code_symbols", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.DatabaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SourceSymbolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("SourceSymbolId");

                    b.ToTable("database_entities", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.DatabaseRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("SourceEntityId");

                    b.HasIndex("TargetEntityId");

                    b.ToTable("database_relationships", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Dependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("dependencies", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("SourceFileId");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("FilePath");

                    b.ToTable("evidences", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceLocation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.SourceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("AnalysisId", "Path");

                    b.ToTable("source_files", (string)null);
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Analysis", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Repository", "Repository")
                        .WithMany("Analyses")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.AnalysisIssue", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Issues")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.ApiEndpoint", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("ApiEndpoints")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RepoLens.Domain.Entities.Project", "Project")
                        .WithMany("ApiEndpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.CodeSymbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Analysis");

                    b.Navigation("Evidence");

                    b.Navigation("Project");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.CodeSymbol", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.SourceFile", "SourceFile")
                        .WithMany("Symbols")
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceFile");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.DatabaseEntity", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("DatabaseEntities")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.CodeSymbol", "SourceSymbol")
                        .WithMany()
                        .HasForeignKey("SourceSymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Analysis");

                    b.Navigation("SourceSymbol");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.DatabaseRelationship", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("DatabaseRelationships")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RepoLens.Domain.Entities.DatabaseEntity", "SourceEntity")
                        .WithMany()
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.DatabaseEntity", "TargetEntity")
                        .WithMany()
                        .HasForeignKey("TargetEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Evidence");

                    b.Navigation("SourceEntity");

                    b.Navigation("TargetEntity");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Dependency", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Dependencies")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Analysis");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RepoLens.Domain.Entities.SourceFile", "SourceFile")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Analysis");

                    b.Navigation("Evidence");

                    b.Navigation("SourceFile");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Evidences")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Project", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Projects")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.SourceFile", b =>
                {
                    b.HasOne("RepoLens.Domain.Entities.Analysis", "Analysis")
                        .WithMany("SourceFiles")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Domain.Entities.Project", "Project")
                        .WithMany("SourceFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("ApiEndpoints");

                    b.Navigation("DatabaseEntities");

                    b.Navigation("DatabaseRelationships");

                    b.Navigation("Dependencies");

                    b.Navigation("DocumentChunks");

                    b.Navigation("Evidences");

                    b.Navigation("Issues");

                    b.Navigation("Projects");

                    b.Navigation("SourceFiles");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Project", b =>
                {
                    b.Navigation("ApiEndpoints");

                    b.Navigation("SourceFiles");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("RepoLens.Domain.Entities.SourceFile", b =>
                {
                    b.Navigation("DocumentChunks");

                    b.Navigation("Symbols");
                });
#pragma warning restore 612, 618
        }
    }
}
